sources:
- name: Travel + Leisure
  active: false
  quality_score: 8.5
  category: luxury
  url: https://www.travelandleisure.com/feed
  last_checked: '2025-01-15T18:02:44.087402'
  error: 'HTTP error: 404 Client Error: Not Found for url: https://www.travelandleisure.com/feed'
- name: Nomadic Matt
  active: true
  quality_score: 8.0
  category: budget
  url: https://www.nomadicmatt.com/feed
  last_checked: '2025-01-16T17:32:23.277160'
  error: null
- name: The Points Guy
  active: true
  quality_score: 9
  category: travel_tips
  url: https://thepointsguy.com/feed
  last_checked: '2025-01-16T17:32:24.332566'
  error: null
- name: A Walk in the World
  active: true
  quality_score: 9
  category: travel_tips
  url: http://awalkintheworld.com/feed/
  last_checked: '2025-01-16T17:32:26.794755'
  error: null
- name: Against the Compass
  active: true
  quality_score: 9
  category: travel_tips
  url: https://againstthecompass.com/en/travel-blog/feed/
  last_checked: '2025-01-16T17:32:34.115349'
  error: null
- name: Travel Zoo
  active: false
  quality_score: 9
  category: travel_tips
  url: https://www.travelzoo.com/feed/
  last_checked: '2025-01-15T17:14:15.899302'
  error: Request timed out
- name: Travel Free
  active: true
  quality_score: 9
  category: travel_tips
  url: https://travelfree.info/feed/
  last_checked: '2025-01-16T17:32:34.774974'
  error: null
- name: The Flight Deal
  active: true
  quality_score: 9
  category: travel_tips
  url: https://feeds.feedburner.com/TheFlightDeal/
  last_checked: '2025-01-16T17:32:35.170543'
  error: null
- name: Thrift Traveler
  active: true
  quality_score: 9
  category: travel_tips
  url: https://thriftytraveler.com/feed/
  last_checked: '2025-01-16T17:32:35.702263'
  error: null
- name: Fly Deal Fare
  active: true
  quality_score: 9
  category: travel_tips
  url: https://blog.flydealfare.com/feed/
  last_checked: '2025-01-16T17:32:36.599932'
  error: null
