sources:
- name: Travel + Leisure
  active: false
  quality_score: 8
  category: luxury
  url: https://www.travelandleisure.com/feed
  last_checked: '2025-01-15T18:02:44.087402'
  error: 'HTTP error: 404 Client Error: Not Found for url: https://www.travelandleisure.com/feed'
  type: rss
- name: Nomadic Matt
  active: true
  quality_score: 8
  category: budget
  url: https://www.nomadicmatt.com/feed
  last_checked: '2025-02-06T16:15:48.439350'
  type: rss
- name: The Points Guy
  active: true
  quality_score: 9
  category: travel_tips
  url: https://thepointsguy.com/feed
  last_checked: '2025-02-06T16:15:49.112797'
  type: rss
- name: A Walk in the World
  active: true
  quality_score: 9
  category: travel_tips
  url: http://awalkintheworld.com/feed/
  last_checked: '2025-02-06T16:15:51.289760'
  type: rss
- name: Against the Compass
  active: true
  quality_score: 9
  category: travel_tips
  url: https://againstthecompass.com/en/travel-blog/feed/
  last_checked: '2025-02-06T16:15:55.829312'
  type: rss
- name: Travel Zoo
  active: false
  quality_score: 9
  category: travel_tips
  url: https://www.travelzoo.com/feed/
  last_checked: '2025-01-15T17:14:15.899302'
  error: Request timed out
  type: rss
- name: Travel Free
  active: true
  quality_score: 9
  category: travel_tips
  url: https://travelfree.info/feed/
  last_checked: '2025-02-06T16:15:56.373089'
  type: rss
- name: The Flight Deal
  active: true
  quality_score: 9
  category: travel_tips
  url: https://feeds.feedburner.com/TheFlightDeal/
  last_checked: '2025-02-06T16:15:56.942638'
  type: rss
- name: Thrift Traveler
  active: true
  quality_score: 9
  category: travel_tips
  url: https://thriftytraveler.com/feed/
  last_checked: '2025-02-06T16:15:57.862903'
  type: rss
- name: Fly Deal Fare
  active: false
  quality_score: 9
  category: travel_tips
  url: https://blog.flydealfare.com/feed/
  last_checked: '2025-01-29T19:04:18.363700'
  error: 'HTTP error: (''Connection aborted.'', RemoteDisconnected(''Remote end closed
    connection without response''))'
  type: rss
- name: Daily Drop
  active: true
  quality_score: 10
  category: travel_tips
  url: today@travel.dailydrop.com
  last_checked: '2025-02-06T16:16:02.345748'
  type: email
  password: BYTE_SIZE_GMAIL_APP_PASSWORD
  provider: BYTE_SIZE_AGGREGATOR
- name: Southwest Airlines
  active: true
  quality_score: 10
  category: travel_tips
  url: SouthwestAirlines@iluv.southwest.com
  last_checked: '2025-02-06T16:16:06.931979'
  type: email
  password: BYTE_SIZE_GMAIL_APP_PASSWORD
  provider: BYTE_SIZE_AGGREGATOR
- name: Jacks Flight Club
  active: true
  quality_score: 10
  category: travel_tips
  url: jack@content.jacksflightclub.com
  last_checked: '2025-02-06T16:16:13.266913'
  type: email
  password: BYTE_SIZE_GMAIL_APP_PASSWORD
  provider: BYTE_SIZE_AGGREGATOR
- name: Jet Blue Airways
  active: true
  quality_score: 10
  category: travel_tips
  url: jetblueairways@email.jetblue.com
  last_checked: '2025-02-06T16:16:17.987774'
  type: email
  password: BYTE_SIZE_GMAIL_APP_PASSWORD
  provider: BYTE_SIZE_AGGREGATOR
- name: Going
  active: true
  quality_score: 10
  category: travel_tips
  url: hello@deals.going.com
  last_checked: '2025-02-06T16:16:22.641616'
  type: email
  password: BYTE_SIZE_GMAIL_APP_PASSWORD
  provider: BYTE_SIZE_AGGREGATOR
- name: Dollar Flight Club
  active: true
  quality_score: 10
  category: travel_tips
  url: jesse@dollarflightclub.com
  last_checked: '2025-02-06T16:16:27.320677'
  type: email
  password: BYTE_SIZE_GMAIL_APP_PASSWORD
  provider: BYTE_SIZE_AGGREGATOR
- name: Dollar Flight Club (Navigator)
  active: true
  quality_score: 10
  category: travel_tips
  url: navigator@dollarflightclub.com
  last_checked: '2025-02-06T16:16:32.010353'
  type: email
  password: BYTE_SIZE_GMAIL_APP_PASSWORD
  provider: BYTE_SIZE_AGGREGATOR
- name: Dollar Flight Club (Smart Points)
  active: true
  quality_score: 10
  category: travel_tips
  url: smartpoints@dollarflightclub.com
  last_checked: '2025-02-06T16:16:36.715262'
  type: email
  password: BYTE_SIZE_GMAIL_APP_PASSWORD
  provider: BYTE_SIZE_AGGREGATOR
- name: Lonely Planet
  active: true
  quality_score: 10
  category: travel_tips
  url: info@mail.lonelyplanet.com
  last_checked: '2025-02-06T16:16:40.332169'
  type: email
  password: BYTE_SIZE_GMAIL_APP_PASSWORD
  provider: BYTE_SIZE_AGGREGATOR
- name: Jacks Flight Club (Detour)
  active: true
  quality_score: 10
  category: travel_tips
  url: detour@travel.jacksflightclub.com
  last_checked: '2025-02-06T16:16:44.485216'
  type: email
  password: BYTE_SIZE_GMAIL_APP_PASSWORD
  provider: BYTE_SIZE_AGGREGATOR
