sources:
- name: Travel + Leisure
  active: false
  quality_score: 8
  category: luxury
  url: https://www.travelandleisure.com/feed
  last_checked: '2025-01-15T18:02:44.087402'
  error: 'HTTP error: 404 Client Error: Not Found for url: https://www.travelandleisure.com/feed'
  type: rss
- name: Nomadic Matt
  active: true
  quality_score: 8
  category: budget
  url: https://www.nomadicmatt.com/feed
  last_checked: '2025-02-06T16:49:16.006467'
  type: rss
- name: The Points Guy
  active: true
  quality_score: 9
  category: travel_tips
  url: https://thepointsguy.com/feed
  last_checked: '2025-02-06T16:49:16.595633'
  type: rss
- name: A Walk in the World
  active: true
  quality_score: 9
  category: travel_tips
  url: http://awalkintheworld.com/feed/
  last_checked: '2025-02-06T16:49:19.123819'
  type: rss
- name: Against the Compass
  active: true
  quality_score: 9
  category: travel_tips
  url: https://againstthecompass.com/en/travel-blog/feed/
  last_checked: '2025-02-06T16:49:23.593004'
  type: rss
- name: Travel Zoo
  active: false
  quality_score: 9
  category: travel_tips
  url: https://www.travelzoo.com/feed/
  last_checked: '2025-01-15T17:14:15.899302'
  error: Request timed out
  type: rss
- name: Travel Free
  active: true
  quality_score: 9
  category: travel_tips
  url: https://travelfree.info/feed/
  last_checked: '2025-02-06T16:49:24.114653'
  type: rss
- name: The Flight Deal
  active: true
  quality_score: 9
  category: travel_tips
  url: https://feeds.feedburner.com/TheFlightDeal/
  last_checked: '2025-02-06T16:49:24.535707'
  type: rss
- name: Thrift Traveler
  active: true
  quality_score: 9
  category: travel_tips
  url: https://thriftytraveler.com/feed/
  last_checked: '2025-02-06T16:49:25.183159'
  type: rss
- name: Fly Deal Fare
  active: false
  quality_score: 9
  category: travel_tips
  url: https://blog.flydealfare.com/feed/
  last_checked: '2025-01-29T19:04:18.363700'
  error: 'HTTP error: (''Connection aborted.'', RemoteDisconnected(''Remote end closed
    connection without response''))'
  type: rss
- name: Daily Drop
  active: true
  quality_score: 10
  category: travel_tips
  url: today@travel.dailydrop.com
  last_checked: '2025-02-06T16:49:29.959155'
  type: email
  password: BYTE_SIZE_GMAIL_APP_PASSWORD
  provider: BYTE_SIZE_AGGREGATOR
- name: Southwest Airlines
  active: true
  quality_score: 10
  category: travel_tips
  url: SouthwestAirlines@iluv.southwest.com
  last_checked: '2025-02-06T16:49:34.832727'
  type: email
  password: BYTE_SIZE_GMAIL_APP_PASSWORD
  provider: BYTE_SIZE_AGGREGATOR
- name: Jacks Flight Club
  active: true
  quality_score: 10
  category: travel_tips
  url: jack@content.jacksflightclub.com
  last_checked: '2025-02-06T16:49:39.514761'
  type: email
  password: BYTE_SIZE_GMAIL_APP_PASSWORD
  provider: BYTE_SIZE_AGGREGATOR
- name: Jet Blue Airways
  active: true
  quality_score: 10
  category: travel_tips
  url: jetblueairways@email.jetblue.com
  last_checked: '2025-02-06T16:49:43.850339'
  type: email
  password: BYTE_SIZE_GMAIL_APP_PASSWORD
  provider: BYTE_SIZE_AGGREGATOR
- name: Going
  active: true
  quality_score: 10
  category: travel_tips
  url: hello@deals.going.com
  last_checked: '2025-02-06T16:49:48.670947'
  type: email
  password: BYTE_SIZE_GMAIL_APP_PASSWORD
  provider: BYTE_SIZE_AGGREGATOR
- name: Dollar Flight Club
  active: true
  quality_score: 10
  category: travel_tips
  url: jesse@dollarflightclub.com
  last_checked: '2025-02-06T16:49:53.046418'
  type: email
  password: BYTE_SIZE_GMAIL_APP_PASSWORD
  provider: BYTE_SIZE_AGGREGATOR
- name: Dollar Flight Club (Navigator)
  active: true
  quality_score: 10
  category: travel_tips
  url: navigator@dollarflightclub.com
  last_checked: '2025-02-06T16:49:58.350239'
  type: email
  password: BYTE_SIZE_GMAIL_APP_PASSWORD
  provider: BYTE_SIZE_AGGREGATOR
- name: Dollar Flight Club (Smart Points)
  active: true
  quality_score: 10
  category: travel_tips
  url: smartpoints@dollarflightclub.com
  last_checked: '2025-02-06T16:50:02.489522'
  type: email
  password: BYTE_SIZE_GMAIL_APP_PASSWORD
  provider: BYTE_SIZE_AGGREGATOR
- name: Lonely Planet
  active: true
  quality_score: 10
  category: travel_tips
  url: info@mail.lonelyplanet.com
  last_checked: '2025-02-06T16:50:06.276542'
  type: email
  password: BYTE_SIZE_GMAIL_APP_PASSWORD
  provider: BYTE_SIZE_AGGREGATOR
- name: Jacks Flight Club (Detour)
  active: true
  quality_score: 10
  category: travel_tips
  url: detour@travel.jacksflightclub.com
  last_checked: '2025-02-06T16:50:09.034915'
  type: email
  password: BYTE_SIZE_GMAIL_APP_PASSWORD
  provider: BYTE_SIZE_AGGREGATOR
