sources:
- name: Travel + Leisure
  active: false
  quality_score: 8.5
  category: luxury
  url: https://www.travelandleisure.com/feed
  last_checked: '2025-01-15T18:02:44.087402'
  error: 'HTTP error: 404 Client Error: Not Found for url: https://www.travelandleisure.com/feed'
- name: Nomadic Matt
  active: true
  quality_score: 8.0
  category: budget
  url: https://www.nomadicmatt.com/feed
  last_checked: '2025-01-15T18:02:49.287172'
  error: null
- name: The Points Guy
  active: true
  quality_score: 9
  category: travel_tips
  url: https://thepointsguy.com/feed
  last_checked: '2025-01-15T18:02:49.708489'
  error: null
- name: A Walk in the World
  active: true
  quality_score: 9
  category: travel_tips
  url: http://awalkintheworld.com/feed/
  last_checked: '2025-01-15T18:02:51.569291'
  error: null
- name: Against the Compass
  active: true
  quality_score: 9
  category: travel_tips
  url: https://againstthecompass.com/en/travel-blog/feed/
  last_checked: '2025-01-15T18:02:57.846212'
  error: null
- name: Travel Zoo
  active: false
  quality_score: 9
  category: travel_tips
  url: https://www.travelzoo.com/feed/
  last_checked: '2025-01-15T17:14:15.899302'
  error: Request timed out
- name: Travel Free
  active: true
  quality_score: 9
  category: travel_tips
  url: https://travelfree.info/feed/
  last_checked: '2025-01-15T18:02:58.190107'
  error: null
- name: The Flight Deal
  active: true
  quality_score: 9
  category: travel_tips
  url: https://feeds.feedburner.com/TheFlightDeal/
  last_checked: '2025-01-15T18:02:58.470795'
  error: null
- name: Thrift Traveler
  active: true
  quality_score: 9
  category: travel_tips
  url: https://thriftytraveler.com/feed/
  last_checked: '2025-01-15T18:02:59.114997'
  error: null
- name: Fly Deal Fare
  active: true
  quality_score: 9
  category: travel_tips
  url: https://blog.flydealfare.com/feed/
  last_checked: '2025-01-15T18:02:59.775983'
  error: null
