sources:
- name: Travel + Leisure
  active: false
  quality_score: 8.5
  category: luxury
  url: https://www.travelandleisure.com/feed
  last_checked: '2025-01-15T18:02:44.087402'
  error: 'HTTP error: 404 Client Error: Not Found for url: https://www.travelandleisure.com/feed'
  type: rss
- name: Nomadic Matt
  active: true
  quality_score: 8.0
  category: budget
  url: https://www.nomadicmatt.com/feed
  last_checked: '2025-01-22T20:55:38.205029'
  error: null
  type: rss
- name: The Points Guy
  active: true
  quality_score: 9
  category: travel_tips
  url: https://thepointsguy.com/feed
  last_checked: '2025-01-22T20:55:39.164705'
  error: null
  type: rss
- name: A Walk in the World
  active: true
  quality_score: 9
  category: travel_tips
  url: http://awalkintheworld.com/feed/
  last_checked: '2025-01-22T20:55:41.619997'
  error: null
  type: rss
- name: Against the Compass
  active: true
  quality_score: 9
  category: travel_tips
  url: https://againstthecompass.com/en/travel-blog/feed/
  last_checked: '2025-01-22T20:55:48.200773'
  error: null
  type: rss
- name: Travel Zoo
  active: false
  quality_score: 9
  category: travel_tips
  url: https://www.travelzoo.com/feed/
  last_checked: '2025-01-15T17:14:15.899302'
  error: Request timed out
  type: rss
- name: Travel Free
  active: true
  quality_score: 9
  category: travel_tips
  url: https://travelfree.info/feed/
  last_checked: '2025-01-22T20:55:48.807739'
  error: null
  type: rss
- name: The Flight Deal
  active: true
  quality_score: 9
  category: travel_tips
  url: https://feeds.feedburner.com/TheFlightDeal/
  last_checked: '2025-01-22T20:55:49.312452'
  error: null
  type: rss
- name: Thrift Traveler
  active: true
  quality_score: 9
  category: travel_tips
  url: https://thriftytraveler.com/feed/
  last_checked: '2025-01-22T20:55:49.945884'
  error: null
  type: rss
- name: Fly Deal Fare
  active: true
  quality_score: 9
  category: travel_tips
  url: https://blog.flydealfare.com/feed/
  last_checked: '2025-01-22T20:55:51.145693'
  error: null
  type: rss
- name: Daily Drop
  active: false
  quality_score: 10
  category: travel_tips
  url: today@travel.dailydrop.com
  last_checked: '2025-01-22T20:55:51.145899'
  error: 
  type: email
  pass: BYTE_SIZE_GMAIL_APP_PASSWORD
  provider: BYTE_SIZE_AGGREGATOR
